// This file is auto-generated by vite-plugin-sync-routes
// DO NOT EDIT MANUALLY - Changes will be overwritten

/**
 * Reserved route names from the frontend application.
 * These names should not be used for dynamic user-generated slugs.
 */
export const RESERVED_ROUTE_NAMES = [
  'api',
  'dashboard',
  'forgot-password',
  'login',
  'reset-password',
  'signup',
] as const

/**
 * Check if a name is a reserved route name.
 * @param name - The name to check
 * @returns true if the name is reserved, false otherwise
 */
export function isReservedRouteName(name: string): boolean {
  return RESERVED_ROUTE_NAMES.includes(name as typeof RESERVED_ROUTE_NAMES[number])
}
